version: '3'

services:
  alarme-app:
    build: .
    container_name: alarme-app
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /app
    network_mode: host
    privileged: true
    entrypoint: sh -c "npm i && tail -f /dev/null"
